config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  mount ActionCable.server, at: '/cable'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/chat', to: 'chat#room'
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # updates the online attribute to true on the db
  def online!
    unless self.admin
      self.online =true
      self.save
    end
  end

  # checks the quantity of users that is online, e.g. how many users that have the attribute
  # online as true on the db. If it's equals to 1, he can access the chat, if it's not,
  # the user can't access the chat. 
  def online_check
    User.where(online: true).count == 1
  end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController

  def room

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  # checks if the user is an admin
  def admin?
    current_user.admin if current_user
  end

  # checks if the user status is true, e.g. if the status attribute is true on the db
  def status_ok?
    current_user.status if current_user
  end

  # checks if the user is online, e.g. if the online attribute is true on the db
  def online_check
    User.where(online: true).count == 2
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/_message_form.html.erb
<div class="message-input">
  <form>
    <div class="form-group">
      <%= hidden_field_tag "message_user_id", current_user.id %>
      <textarea class="form-control" type="text" data-behavior="room_speaker" data-remote="true" rows="4"></textarea>
      <button id="chat-button" class="btn btn-primary pull-right">Submit</button>
    </div>  
  </form>
  
  <div class="auto-scroll">
    <%= label_tag "auto-scroll" %>
    <%= check_box_tag "auto-scroll" %>
  </div> 
  
  <%= link_to "Exit", root_path, class: "btn btn-lg btn-danger" %>
 
</div>

app/views/chat/_messages.html.erb
<div id="messages" class="messages">
  <div class="row">
    <div class="col-md-6">
      <div class="message-admin">
        <h5 class="text-primary" id="message-head-admin">leandrobiciato58@gmail.com:</h5>
        <p id="message-parag">Hello there !!!
                                Be welcome and feel free to say whatever you want, i'm here to listen to you !!!
        </p>
      </div>
    </div>
  </div>'
</div>

app/views/chat/_users_online_list.html.erb
<div class="users-online"></div>

app/views/chat/room.html.erb
<div class="messages-set">
  <%= render 'messages' %>
  <%= render 'message_form' %>
</div>
<% if current_user.admin %>
  <button id="update-online">Update online</button>
  <button id="direct-user">Direct User</button>
  <%= render 'users_online_list' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Vent Online 
    by <em>Leandro Biciato</em>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color: lightblue;"">
  <div class="container">
    <%= link_to "Vent Online", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vent Online</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <meta name="turbolinks-visit-control" content="reload">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  If you find any trouble with the page, contact me by e-mail: leandrobiciato58@gmail.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Please, send me an e-mail if you're having trouble with the page: leandrobiciato58@gmail.com
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Vent Online</h1>

  <h2>
    Here is a site for you to talk whatever you want with someone willing to hear
      whatever you have to say.
  </h2>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="alert alert-danger" role="alert">
  - It's simple, just sign up and then, all you have to do is click on the chat link and you'll be directed to the chat's page.
</div>
<div class="row">
  <div class="col-sm-3">
    <div class="card" style="width: 22rem;">
      <%= image_tag "clock.jpg", size: "220x180", class: "card-img-top" %>
      <div class="card-body">
        <p class="card-text alert alert-danger text-justify" role="alert">The session will be limited to 1 hour to make possible for the site to attend others people</p>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card" style="width: 22rem;">
      <%= image_tag "calendar.jpg", size: "220x180", class: "card-img-top" %>
      <div class="card-body">
        <p class="card-text alert alert-danger text-justify" role="alert">I'll be available for chatting from monday to friday and from 11:00am to 8:00pm (London Time).</p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="chat-link mt-2">
      <% if user_signed_in? %>
          <%= link_to "CHAT AVAILABLE", chat_url, class: "btn btn-lg btn-success" %>
      <% end %>  
    </div>
  </div>
</div>

app/views/users/sign_up.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>